// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDQnliSl0yS3qDxQu3uSY1lvikimzWInN8",
      authDomain: "dap-2024-final-project.firebaseapp.com",
      projectId: "dap-2024-final-project",
      storageBucket: "dap-2024-final-project.firebasestorage.app",
      messagingSenderId: "725729088217",
      appId: "1:725729088217:web:55c1196791fd08dcade4c8");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgmQ5dEn_fSAml0BPO4aRvXPjtBAdbzO8',
    appId: '1:725729088217:android:9e10653dbc2e59eaade4c8',
    messagingSenderId: '725729088217',
    projectId: 'dap-2024-final-project',
    storageBucket: 'dap-2024-final-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmQ5dEn_fSAml0BPO4aRvXPjtBAdbzO8',
    appId: '1:725729088217:ios:15c8b581acca0a99ade4c8',
    messagingSenderId: '725729088217',
    projectId: 'dap-2024-final-project',
    storageBucket: 'dap-2024-final-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmQ5dEn_fSAml0BPO4aRvXPjtBAdbzO8',
    appId: '1:725729088217:ios:15c8b581acca0a99ade4c8',
    messagingSenderId: '725729088217',
    projectId: 'dap-2024-final-project',
    storageBucket: 'dap-2024-final-project.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyDQnliSl0yS3qDxQu3uSY1lvikimzWInN8",
      authDomain: "dap-2024-final-project.firebaseapp.com",
      projectId: "dap-2024-final-project",
      storageBucket: "dap-2024-final-project.firebasestorage.app",
      messagingSenderId: "725729088217",
      appId: "1:725729088217:web:e55c8db32c6b7ddaade4c8");
}
